### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by pshanoop** [archlinux/alpm.rs#27]
Current master  f2768ea, and tag `alpm-v2.1.3` build fails with this error 
```
❯ cargo build
   Compiling pkg-config v0.3.22
   Compiling cini v0.1.1
   Compiling bitflags v1.3.2
   Compiling pacmanconf v1.0.0
   Compiling alpm-sys v2.1.2 (/tmp/tmp.lSWwTHHApn/alpm.rs/alpm-sys)
   Compiling alpm v2.1.3 (/tmp/tmp.lSWwTHHApn/alpm.rs/alpm)
error: doc alias attribute expects a string: #[doc(alias = "0")]
  --> alpm/src/db.rs:13:7
   |
13 | #[doc(alias("repo", "repository"))]
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `alpm`

To learn more, run the command again with --verbose.
```

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/paru/issues/586

**Comment by Morganamilo** [comment]
Actually https://github.com/Morganamilo/paru/issues/575

They both have the same issue title.

**Comment by pshanoop** [comment]
> Actually [Morganamilo/paru#575](https://github.com/Morganamilo/paru/issues/575)
> 
> They both have the same issue title.

Sorry, didn't check there, thought this would be starting place. :)

Updating rust fixed it 👍🏾
