### ISSUE TITLE
alpm.rs 3.0.4 fails to build with pacman 6.1.0

### ISSUE THREAD

**Issue by Ramenu** [archlinux/alpm.rs#40]
since libalpm.so.13 has been replaced with libalpm.so.14, the alpm crate fails to compile: `error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory`

**Comment by Morganamilo** [comment]
That's a runtime error from a binary that was linked against libalpm 13e Alpm V3 targets libalpm 14 and should compile fine.

**Comment by Ramenu** [comment]
You're right. I had to rebuild the entire project from scratch in order for it to work. Thanks.
