### ISSUE TITLE
libalpm v15

### ISSUE THREAD

**Issue by kescherCode** [archlinux/alpm.rs#48]
libalpm v15 was released along with pacman 7.x.

**Comment by fosskers** [comment]
v4 already accounts for that, actually.

**Comment by kescherCode** [comment]
Ah, fair.

README needs an update in that case

**Comment by keilmillerjr** [comment]
The latest commit says we are at [alpm-utils v4.0.1](https://github.com/archlinux/alpm.rs/commit/e5fdc86b8864228dffd78431883461dcc35cfde2), but the latest tag release is still at [alpm-v3.0.2](https://github.com/archlinux/alpm.rs/releases/tag/alpm-v3.0.2). Can we get another tag release? This is holding back other projects that rely on this tool.

@kescherCode https://github.com/archlinux/alpm.rs/pull/47
